#!/bin/bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install nglview-js-widgets 
jupyter labextension install jupyter-matplotlib
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode
git clone https://github.com/Zulko/vapory.git
cd vapory
pip install -e .
cd ..
jupyter lab build --dev-build=False --minimize=False
cp jupyter_notebook_config.py ~/.jupyter 
